CREATE TABLE accounts
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(40),
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by   VARCHAR(40),
    balance            DECIMAL(15, 2)                          NOT NULL,
    currency           SMALLINT                                NOT NULL,
    sub_ledger_id      BIGINT,
    customer_id        BIGINT,
    CONSTRAINT pk_accounts PRIMARY KEY (id)
);

CREATE TABLE cities
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(40),
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by   VARCHAR(40),
    name               VARCHAR(100),
    display_order      INTEGER,
    province_id        BIGINT,
    CONSTRAINT pk_cities PRIMARY KEY (id)
);

CREATE TABLE countries
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date          TIMESTAMP WITHOUT TIME ZONE,
    created_by            VARCHAR(40),
    last_modified_date    TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by      VARCHAR(40),
    name                  VARCHAR(80),
    two_letter_iso_code   VARCHAR(2),
    three_letter_iso_code VARCHAR(3),
    numeric_iso_code      INTEGER,
    display_order         INTEGER,
    CONSTRAINT pk_countries PRIMARY KEY (id)
);

CREATE TABLE customer_addresses
(
    customer_id        BIGINT NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(40),
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by   VARCHAR(40),
    alias              VARCHAR(50),
    first_name         VARCHAR(40),
    last_name          VARCHAR(80),
    company            VARCHAR(80),
    address1           VARCHAR(200),
    address2           VARCHAR(200),
    zip_postal_code    VARCHAR(20),
    phone_number       VARCHAR(20),
    fax_number         VARCHAR(20),
    latitude           DOUBLE PRECISION,
    longitude          DOUBLE PRECISION,
    country_id         BIGINT,
    province_id        BIGINT,
    city_id            BIGINT
);

CREATE TABLE customer_attributes
(
    customer_id        BIGINT NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(40),
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by   VARCHAR(40),
    attr_group         VARCHAR(21),
    attr_key           VARCHAR(21),
    attr_value         VARCHAR(200)
);

CREATE TABLE customers
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(40),
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by   VARCHAR(40),
    first_name         VARCHAR(40)                             NOT NULL,
    last_name          VARCHAR(80)                             NOT NULL,
    address            VARCHAR(100)                            NOT NULL,
    CONSTRAINT pk_customers PRIMARY KEY (id)
);

CREATE TABLE general_ledgers
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(40),
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by   VARCHAR(40),
    code               VARCHAR(20)                             NOT NULL,
    title              VARCHAR(40)                             NOT NULL,
    description        VARCHAR(250),
    is_active          BOOLEAN                                 NOT NULL,
    ledger_type        SMALLINT                                NOT NULL,
    ledger_nature      SMALLINT                                NOT NULL,
    ledger_id          BIGINT,
    CONSTRAINT pk_general_ledgers PRIMARY KEY (id)
);

CREATE TABLE installments
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date        TIMESTAMP WITHOUT TIME ZONE,
    created_by          VARCHAR(40),
    last_modified_date  TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by    VARCHAR(40),
    installment_no      INTEGER                                 NOT NULL,
    due_date            date                                    NOT NULL,
    principal_amount    DECIMAL(15, 2)                          NOT NULL,
    interest_amount     DECIMAL(15, 2)                          NOT NULL,
    total_amount        DECIMAL(15, 2)                          NOT NULL,
    loan_balance_amount DECIMAL(15, 2)                          NOT NULL,
    currency            SMALLINT                                NOT NULL,
    paid_date           TIMESTAMP WITHOUT TIME ZONE,
    paid                BOOLEAN                                 NOT NULL,
    loan_id             BIGINT                                  NOT NULL,
    CONSTRAINT pk_installments PRIMARY KEY (id)
);

CREATE TABLE ledgers
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(40),
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by   VARCHAR(40),
    code               VARCHAR(20)                             NOT NULL,
    title              VARCHAR(40)                             NOT NULL,
    description        VARCHAR(250),
    is_active          BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_ledgers PRIMARY KEY (id)
);

CREATE TABLE loan_conditions
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date        TIMESTAMP WITHOUT TIME ZONE,
    created_by          VARCHAR(40),
    last_modified_date  TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by    VARCHAR(40),
    interest_rate       DECIMAL(7, 2)                           NOT NULL,
    min_refund_duration INTEGER                                 NOT NULL,
    max_refund_duration INTEGER                                 NOT NULL,
    min_amount          DECIMAL(15, 2)                          NOT NULL,
    max_amount          DECIMAL(15, 2)                          NOT NULL,
    currency            SMALLINT                                NOT NULL,
    start_date          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    expire_date         TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_loan_conditions PRIMARY KEY (id)
);

CREATE TABLE loans
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date        TIMESTAMP WITHOUT TIME ZONE,
    created_by          VARCHAR(40),
    last_modified_date  TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by    VARCHAR(40),
    amount              DECIMAL(15, 2)                          NOT NULL,
    interest_rate       DECIMAL(7, 2)                           NOT NULL,
    refund_duration     INTEGER                                 NOT NULL,
    request_date        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    deposit_date        TIMESTAMP WITHOUT TIME ZONE,
    first_payment_date  date,
    currency            SMALLINT                                NOT NULL,
    paid                BOOLEAN                                 NOT NULL,
    customer_id         BIGINT                                  NOT NULL,
    customer_account_id BIGINT                                  NOT NULL,
    loan_account_id     BIGINT                                  NOT NULL,
    CONSTRAINT pk_loans PRIMARY KEY (id)
);

CREATE TABLE provinces
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(40),
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by   VARCHAR(40),
    name               VARCHAR(100),
    abbreviation       VARCHAR(10),
    display_order      INTEGER,
    country_id         BIGINT,
    CONSTRAINT pk_provinces PRIMARY KEY (id)
);

CREATE TABLE rules
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(40),
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by   VARCHAR(40),
    name               VARCHAR(255),
    content            VARCHAR(255),
    CONSTRAINT pk_rules PRIMARY KEY (id)
);

CREATE TABLE sub_ledgers
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(40),
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by   VARCHAR(40),
    code               VARCHAR(20)                             NOT NULL,
    title              VARCHAR(40)                             NOT NULL,
    description        VARCHAR(250),
    is_active          BOOLEAN                                 NOT NULL,
    ledger_type        SMALLINT                                NOT NULL,
    ledger_nature      SMALLINT                                NOT NULL,
    general_ledger_id  BIGINT,
    CONSTRAINT pk_sub_ledgers PRIMARY KEY (id)
);

CREATE TABLE transactions
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(40),
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by   VARCHAR(40),
    amount             DECIMAL(15, 2)                          NOT NULL,
    transaction_type   SMALLINT                                NOT NULL,
    reg_date           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    description        VARCHAR(200),
    user_id            BIGINT                                  NOT NULL,
    trace_no           VARCHAR(36)                             NOT NULL,
    currency           SMALLINT                                NOT NULL,
    account_id         BIGINT                                  NOT NULL,
    CONSTRAINT pk_transactions PRIMARY KEY (id)
);

CREATE TABLE users
(
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date               TIMESTAMP WITHOUT TIME ZONE,
    created_by                 VARCHAR(40),
    last_modified_date         TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by           VARCHAR(40),
    username                   VARCHAR(40)                             NOT NULL,
    password                   VARCHAR(256)                            NOT NULL,
    user_type                  SMALLINT                                NOT NULL,
    last_login_date            TIMESTAMP WITHOUT TIME ZONE,
    last_password_changed_date TIMESTAMP WITHOUT TIME ZONE,
    user_state                 SMALLINT,
    failed_attempt             INTEGER,
    lock_time                  TIMESTAMP WITHOUT TIME ZONE,
    access_token               VARCHAR(255),
    refresh_token              VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE general_ledgers
    ADD CONSTRAINT uc_general_ledgers_code UNIQUE (code);

ALTER TABLE ledgers
    ADD CONSTRAINT uc_ledgers_code UNIQUE (code);

ALTER TABLE sub_ledgers
    ADD CONSTRAINT uc_sub_ledgers_code UNIQUE (code);

ALTER TABLE transactions
    ADD CONSTRAINT uc_transactions_trace_no UNIQUE (trace_no);

ALTER TABLE users
    ADD CONSTRAINT uc_users_access_token UNIQUE (access_token);

ALTER TABLE users
    ADD CONSTRAINT uc_users_refresh_token UNIQUE (refresh_token);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE accounts
    ADD CONSTRAINT FK_ACCOUNTS_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customers (id);

ALTER TABLE accounts
    ADD CONSTRAINT FK_ACCOUNTS_ON_SUB_LEDGER FOREIGN KEY (sub_ledger_id) REFERENCES sub_ledgers (id);

ALTER TABLE cities
    ADD CONSTRAINT FK_CITIES_ON_PROVINCE FOREIGN KEY (province_id) REFERENCES provinces (id);

ALTER TABLE general_ledgers
    ADD CONSTRAINT FK_GENERAL_LEDGERS_ON_LEDGER FOREIGN KEY (ledger_id) REFERENCES ledgers (id);

ALTER TABLE installments
    ADD CONSTRAINT FK_INSTALLMENTS_ON_LOAN FOREIGN KEY (loan_id) REFERENCES loans (id);

ALTER TABLE loans
    ADD CONSTRAINT FK_LOANS_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customers (id);

ALTER TABLE loans
    ADD CONSTRAINT FK_LOANS_ON_CUSTOMER_ACCOUNT FOREIGN KEY (customer_account_id) REFERENCES accounts (id);

ALTER TABLE loans
    ADD CONSTRAINT FK_LOANS_ON_LOAN_ACCOUNT FOREIGN KEY (loan_account_id) REFERENCES accounts (id);

ALTER TABLE provinces
    ADD CONSTRAINT FK_PROVINCES_ON_COUNTRY FOREIGN KEY (country_id) REFERENCES countries (id);

ALTER TABLE sub_ledgers
    ADD CONSTRAINT FK_SUB_LEDGERS_ON_GENERAL_LEDGER FOREIGN KEY (general_ledger_id) REFERENCES general_ledgers (id);

ALTER TABLE transactions
    ADD CONSTRAINT FK_TRANSACTIONS_ON_ACCOUNT FOREIGN KEY (account_id) REFERENCES accounts (id);

ALTER TABLE customer_addresses
    ADD CONSTRAINT fk_customer_addresses_on_customer FOREIGN KEY (customer_id) REFERENCES customers (id);

ALTER TABLE customer_attributes
    ADD CONSTRAINT fk_customer_attributes_on_customer FOREIGN KEY (customer_id) REFERENCES customers (id);